# name: Env 

# on: push

# env: 
#   WF_ENV: All jobs

# jobs:
#   log-env:
#     runs-on: ubuntu-latest
#     env: 
#       JOB_ENV: In Job
#     steps:
#       - name: Log
#         run: |
#           echo "WF_ENV: ${WF_ENV}"
#           echo "JOB_ENV: ${JOB_ENV}"